feat(transform): implement picklable transform factories for tiling (#2114)
This pull request refactors the creation of filtering and tiling
transform factories to ensure they are picklable by reference, which is
important for multiprocessing and serialization scenarios. Instead of
returning local closures, the factory functions now return instances of
module-level callable classes.

This is needed for example for dataloaders with multiple workers which
otherwise raise errors like:
AttributeError: Can't get local object
`create_tiling_transform.<locals>.factory`


<!-- Contributing guide:
https://github.com/open-edge-platform/datumaro/blob/develop/contributing.md
-->

<!--
Please add a summary of changes. You may use Copilot to auto-generate
the PR description but please consider including any other relevant
facts which Copilot may be unaware of (such as design choices and
testing procedure).

Add references to the relevant issues and pull requests if any like so:

Resolves #111 and #222.
Depends on #1000 (for series of dependent commits).
-->

### Checklist
<!-- Put an 'x' in all the boxes that apply -->
- [ ] I have added tests to cover my changes or documented any manual
tests.
- [ ] I have updated the
[documentation](https://github.com/open-edge-platform/datumaro/tree/develop/docs)
accordingly

---------

Signed-off-by: Albert van Houten <albert.van.houten@intel.com>